#!/usr/local/bin/python

"""
	Authors: <Stefano Marchesin, Alberto Purpura>
	Copyright: (C) 2019-2020 <http://www.dei.unipd.it/ 
	Department of Information Engineering> (DEI), <http://www.unipd.it/ University of Padua>, Italy
	License: <http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0>
"""

import argparse
import json
import os
import subprocess
import sys

os.system('python ./indexing.py --data_folder /input/collections/ --output_folder /data --stopwords /indri_stopwords.txt')
# os.system('python ./indexing.py --data_folder  /Users/albertopurpura/PycharmProjects/OSIRRC/data/corpus_test/robust04/robust04 --output_folder ./data --stopwords ./indri_stopwords.txt')