#!/usr/local/bin/python
import argparse
import json
import os
import subprocess
import sys

# The number of CPU cores available
cores = os.cpu_count()

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the args")

# Parse the args
args, unknown = parser.parse_known_args()
# args, unknown = parser.parse_known_args(['--json', '{"version": "", "opts": {"data_folder": "/input/collections/", "stopwords": "/indri_stopwords.txt", "output_folder": "/output"}}'])
options = '--index_folder /data --output_ranking_folder /output' + ' --qrels_file ' + args.json['opts']['qrels'] +' --queries_file ' + args.json['topic']['path'] + ' --output_folder /output --splits_test  /output/splits/test_split.txt'
print(options)

os.system('python ./nvsm_test.py ' + options)

# python -u nvsm_test.py --queries_file $1 --qrels_file $2 --splits_test $3 --output_folder $4