#!/usr/local/bin/python
import argparse
import json
import os
import subprocess
import sys

# The number of CPU cores available
cores = os.cpu_count()

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the args")

# Parse the args
args, unknown = parser.parse_known_args()
options = '--model_folder ' + args.json['model_folder']['path'] + ' --qrels_file ' + args.json['qrels']['path'] \
          + ' --queries_file ' + args.json['topic']['path'] \
          + ' --output_folder /data --splits_test  /data/splits/test_split.txt ' \
          + ' --splits_val /data/splits/validation_split.txt'

for k, v in args.json['opts'].items():
    options += ' --' + k + ' ' + v

print(options)
os.system('python ./nvsm_train.py ' + options)

# python indexing.py --data_folder $1 --output_folder $2 --stopwords $3
# 'sh -c \'/train --json "{\\"opts\\": {}, \\"topic\\": {\\"path\\": \\"/input/topics/topics.301-450_601-700.txt\\", \\"format\\": \\"trec\\"}, \\"qrels\\": {\\"path\\": \\"/output/qrels/qrels.qrel\\"}}"\''
