#!/usr/local/bin/python

"""
	Authors: <Stefano Marchesin, Alberto Purpura>
	Copyright: (C) 2019-2020 <http://www.dei.unipd.it/ 
	Department of Information Engineering> (DEI), <http://www.unipd.it/ University of Padua>, Italy
	License: <http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0>
"""
import argparse
import json
import os
import subprocess
import sys

# The number of CPU cores available
cores = os.cpu_count()

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the args")

# Parse the args
args, unknown = parser.parse_known_args()
# args, unknown = parser.parse_known_args(['--json', '{"version": "", "opts": {"data_folder": "/input/collections/", "stopwords": "/indri_stopwords.txt", "output_folder": "/output"}}'])
options = '--index_folder /data --output_ranking_folder /output' + ' --queries_file ' + args.json['topic']['path'] + ' --output_folder /output --splits_test  /data/splits/test_split.txt'
print(options)

os.system('python ./nvsm_test.py ' + options)

# python -u nvsm_test.py --queries_file $1 --qrels_file $2 --splits_test $3 --output_folder $4